[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
authors = ["Soroban IDE"]
description = "A sample Hello World smart contract for Soroban"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-org/soroban-ide"

[lib]
crate-type = ["cdylib"]

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = "22.0.8"

[dev-dependencies]
soroban-sdk = { version = "22.0.8", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true